import json

json_str = {"id": "0oaw0txj8n6m5g6w30h7",
    "name":"ienergycloud_crf598dsifsaml_11",
    "label":"CRF598-DSIF-SAML",
    "status":"ACTIVE",
    "lastUpdated":"2020-12-23T15:11:55.000Z","created":"2020-12-23T15:11:55.000Z",
    "accessibility":{
        "selfService":false,"errorRedirectUrl":null,"loginRedirectUrl":null
    },
    "visibility":{"autoSubmitToolbar":false,"hide":{"iOS":true,"web":true},"appLinks":{"ienergycloud_crf598dsifsaml_11_link":true}},"features":[],"signOnMode":"SAML_2_0","credentials":{"userNameTemplate":
    {"template":"(String.toLowerCase(String.append(String.substring(user.firstName, 0, 1),String.substringBefore(String.substringAfter(user.email, "."),"@"))))","type":"CUSTOM"},"signing":{"kid":"Z1KHstnOBlXJbufa4MiqQYlBJHDYdR9bt_JaBHBV9Ik"}},"settings":{"app":{},"notifications":{"vpn":{"network":{"connection":"DISABLED"},"message":null,"helpUrl":null}},"signOn":{"defaultRelayState":null,"ssoAcsUrl":"https://dssecurity.shpdev01.dawlmkshpdev01.ienergycloud.solutions/auth/realms/DecisionSpace_Integration_Server/broker/okta/endpoint","idpIssuer":"http://www.okta.com/${org.externalKey}","audience":"https://dssecurity.shpdev01.dawlmkshpdev01.ienergycloud.solutions/auth/realms/DecisionSpace_Integration_Server/broker/okta/endpoint","recipient":"https://dssecurity.shpdev01.dawlmkshpdev01.ienergycloud.solutions/auth/realms/DecisionSpace_Integration_Server/broker/okta/endpoint","destination":"https://dssecurity.shpdev01.dawlmkshpdev01.ienergycloud.solutions/auth/realms/DecisionSpace_Integration_Server/broker/okta/endpoint","subjectNameIdTemplate":"${user.userName}","subjectNameIdFormat":"urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified","responseSigned":true,"assertionSigned":true,"signatureAlgorithm":"RSA_SHA256","digestAlgorithm":"SHA256","honorForceAuthn":true,"authnContextClassRef":"urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport","spIssuer":null,"requestCompressed":false,"attributeStatements":[{"type":"EXPRESSION","name":"email","namespace":"urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified","values":["user.email"]},{"type":"EXPRESSION","name":"firstName","namespace":"urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified","values":["user.firstName"]},
    {
        "type":"EXPRESSION","name":"lastName","namespace":"urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified","values":["user.lastName"]
        },{"type":"EXPRESSION","name":"dsis_user","namespace":"urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified","values":["appuser.dsis_user"]},{"type":"EXPRESSION","name":"dsis_admin","namespace":"urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified","values":["appuser.dsis_admin"]},{"type":"EXPRESSION","name":"dwp_user","namespace":"urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified","values":["appuser.dwp_user"]},{"type":"EXPRESSION","name":"dwp_admin","namespace":"urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified","values":["appuser.dwp_admin"]}],"inlineHooks":[],"allowMultipleAcsEndpoints":false,"acsEndpoints":[],"slo":{"enabled":false}}},"_links":{"help":{"href":"https://ienergycloud-admin.oktapreview.com/app/ienergycloud_crf598dsifsaml_11/0oaw0txj8n6m5g6w30h7/setup/help/SAML_2_0/instructions","type":"text/html"},"metadata":{"href":"https://ienergycloud.oktapreview.com/api/v1/apps/0oaw0txj8n6m5g6w30h7/sso/saml/metadata","type":"application/xml"},"appLinks":[{"name":"ienergycloud_crf598dsifsaml_11_link","href":"https://ienergycloud.oktapreview.com/home/ienergycloud_crf598dsifsaml_11/0oaw0txj8n6m5g6w30h7/alnw0u2bdyAEidpSi0h7","type":"text/html"}],"groups":{"href":"https://ienergycloud.oktapreview.com/api/v1/apps/0oaw0txj8n6m5g6w30h7/groups"},"logo":[{"name":"medium","href":"https://op1static.oktacdn.com/assets/img/logos/default.6770228fb0dab49a1695ef440a5279bb.png","type":"image/png"}],"users":{"href":"https://ienergycloud.oktapreview.com/api/v1/apps/0oaw0txj8n6m5g6w30h7/users"},
        "deactivate":{"href":"https://ienergycloud.oktapreview.com/api/v1/apps/0oaw0txj8n6m5g6w30h7/lifecycle/deactivate"}
        }
    }
    
    
    # {"id":"https://ienergycloud.oktapreview.com/meta/schemas/apps/0oaw0txj8n6m5g6w30h7/default","$schema":"http://json-schema.org/draft-04/schema#","name":"ienergycloud_crf598dsifsaml_11","title":"CRF598-DSIF-SAML User","lastUpdated":"2020-12-23T15:11:56.000Z","created":"2020-12-23T15:11:55.000Z","definitions":{"custom":{"id":"#custom","type":"object","properties":{"dsis_user":{"title":"dsis_user","type":"boolean","required":true,"scope":"NONE","master":{"type":"PROFILE_MASTER"}},"dsis_admin":{"title":"dsis_admin","type":"boolean","required":true,"scope":"NONE","master":{"type":"PROFILE_MASTER"}},"dwp_user":{"title":"dwp_user","type":"boolean","required":true,"scope":"NONE","master":{"type":"PROFILE_MASTER"}},"dwp_admin":{"title":"dwp_admin","type":"boolean","required":true,"scope":"NONE","master":{"type":"PROFILE_MASTER"}}},"required":["dsis_user","dsis_admin","dwp_user","dwp_admin"]},"base":{"id":"#base","type":"object","properties":{"userName":{"title":"Username","type":"string","required":true,"scope":"NONE","maxLength":100,"master":{"type":"PROFILE_MASTER"}}},"required":["userName"]}},"type":"object","properties":{"profile":{"allOf":[{"$ref":"#/definitions/custom"}
    
print (s)